<?php

declare(strict_types=1);

namespace Jean85\AdventOfCode\Xmas2017\Day7;

use Jean85\AdventOfCode\SecondPartSolutionInterface;
use Jean85\AdventOfCode\SolutionInterface;

class Day7Solution implements SolutionInterface, SecondPartSolutionInterface
{
    /** @var Tower[] */
    private $input;

    /** @var string[][] */
    private $reverseTowerList;

    /**
     * Day4Solution constructor.
     *
     * @param Tower[] $input
     */
    public function __construct(array $input = null)
    {
        foreach ($input ?? $this->getMyInput() as $tower) {
            $this->input[$tower->getName()] = $tower;
        }
        $this->reverseTowerList = [];
    }

    public function solve()
    {
        $this->buildReverseList();

        foreach ($this->reverseTowerList as $towerName => $supportedBy) {
            if ($supportedBy === []) {
                return $towerName;
            }
        }
    }

    private function buildReverseList()
    {
        foreach ($this->input as $towerName => $tower) {
            $this->reverseTowerList[$towerName] = [];
        }

        foreach ($this->input as $tower) {
            foreach ($tower->getSupports() as $supportedTower) {
                $this->reverseTowerList[$supportedTower][] = $tower->getName();
            }
        }
    }

    public function solveSecondPart()
    {
        $unbalancedSupportingTower = $this->getUnbalancedTower();
        $unbalancedWeights = $this->getSupportedWeights($unbalancedSupportingTower);
        $min = min($unbalancedWeights);
        $max = max($unbalancedWeights);
        $unbalancedTower = $this->findWrongWeight($unbalancedWeights);

        $weightDiff = $max - $min;
        if ($unbalancedTower->getWeight() === $min) {
            return $unbalancedTower->getWeight() + $weightDiff;
        }

        return $unbalancedTower->getWeight() - $weightDiff;
    }

    /**
     * @param int[] $unbalanced
     */
    private function findWrongWeight(array $unbalanced): Tower
    {
        $min = min($unbalanced);
        $max = max($unbalanced);

        foreach ([$min, $max] as $weight) {
            $count = 0;
            $unbalancedTowerName = null;

            foreach ($unbalanced as $towerName => $item) {
                if ($item === $weight) {
                    $unbalancedTowerName = $towerName;
                    ++$count;
                }
            }

            if ($count === 1) {
                return $this->getTowerByName($unbalancedTowerName);
            }
        }
    }

    public function getUnbalancedTower(): Tower
    {
        $tower = $this->getTowerByName($this->solve());

        if ($this->isUnbalanced($tower)) {
            return $tower;
        }

        foreach ($tower->getSupports() as $supportedName) {
            $childTower = $this->getTowerByName($supportedName);
            if ($this->isUnbalanced($childTower)) {
                return $childTower;
            }
        }

        throw new \RuntimeException('Unbalanced tower not found!');
    }

    private function isUnbalanced(Tower $tower)
    {
        $supportedWeights = $this->getSupportedWeights($tower);

        if (empty($supportedWeights)) {
            return false;
        }

        return min($supportedWeights) !== max($supportedWeights);
    }

    /**
     * @return \string[][]
     */
    public function getReverseTowerList(): array
    {
        return $this->reverseTowerList;
    }

    private function getMyInput()
    {
        return [
            new Tower('mmqyju', 156, ['rjzvwv', 'noybkx']),
            new Tower('dvkug', 90, ['tbjbz', 'gxnvl']),
            new Tower('meeiw', 95),
            new Tower('iaibv', 52),
            new Tower('ckddz', 36),
            new Tower('yikfhvr', 52),
            new Tower('phqiqi', 92),
            new Tower('ywctcn', 38),
            new Tower('boofr', 332, ['aqiun', 'zilgfzu']),
            new Tower('zfusug', 65),
            new Tower('yffcj', 90, ['bbmmtud', 'bqbgocl', 'kgntkz', 'mmfwbku', 'asefoiu']),
            new Tower('velbwcl', 432),
            new Tower('liori', 107, ['fzcts', 'wgfbd']),
            new Tower('watknc', 96),
            new Tower('wbpvo', 77, ['dtdkt', 'ixhnyqi']),
            new Tower('mladbjo', 27),
            new Tower('cimsvsq', 69),
            new Tower('ugyjqg', 10),
            new Tower('tmybiz', 55),
            new Tower('ueheft', 12),
            new Tower('awweagx', 26),
            new Tower('zxiqpq', 88),
            new Tower('atcrb', 92),
            new Tower('ocauj', 95),
            new Tower('ayqfub', 306, ['drwyz', 'prssjgo']),
            new Tower('xbeau', 76, ['xxshfpr', 'renhdd']),
            new Tower('tmicb', 21),
            new Tower('uesefn', 59),
            new Tower('kbcztr', 82),
            new Tower('rcssnrj', 89),
            new Tower('ruahai', 23),
            new Tower('gjtfdc', 27),
            new Tower('eknipd', 695, ['lyqumu', 'egjriv', 'ipnwyh']),
            new Tower('cqlnevp', 23),
            new Tower('svibl', 384),
            new Tower('jjvdara', 27),
            new Tower('kpnjwzl', 79),
            new Tower('mhtgqj', 333, ['jzyfyj', 'njbqsh']),
            new Tower('mhxpay', 200, ['zffpdg', 'smhctr']),
            new Tower('cinjgkc', 11),
            new Tower('nvpsm', 135, ['yfjtfc', 'oebjoin', 'phmpasy']),
            new Tower('qxnfz', 29),
            new Tower('smpoeov', 79, ['wygaxkm', 'vjjhef']),
            new Tower('dckpb', 64),
            new Tower('lgsulw', 254, ['kmmtdma', 'luemof']),
            new Tower('sgjljt', 23),
            new Tower('mjverr', 15),
            new Tower('kbhig', 38),
            new Tower('tvranal', 153, ['oyegdcw', 'gjtfdc']),
            new Tower('dresa', 218, ['grcpk', 'uqork']),
            new Tower('kixuhs', 88, ['prjag', 'dnrtq', 'vltxhu', 'lupel']),
            new Tower('adooxhb', 37),
            new Tower('esxbml', 69),
            new Tower('skgciiy', 23),
            new Tower('utnwfrl', 55),
            new Tower('fixda', 59),
            new Tower('jmwrcxe', 88, ['hwvglh', 'rgiaar', 'dypjwz']),
            new Tower('radrzr', 88),
            new Tower('gdbvvx', 36),
            new Tower('rfowq', 266, ['xztwenv', 'gdbvvx']),
            new Tower('qvily', 7),
            new Tower('jvegmwc', 153, ['mladbjo', 'jjvdara']),
            new Tower('qesuv', 303, ['tculi', 'lsgvik', 'boofr']),
            new Tower('xhifoak', 6),
            new Tower('zkhxn', 52),
            new Tower('gjaltuo', 54, ['gffoyh', 'mrzmkae']),
            new Tower('taaibzy', 209, ['xbbygk', 'ysqizk']),
            new Tower('lzzeke', 24, ['tfdwxe', 'kvgsfj', 'lwaoy']),
            new Tower('zspyg', 57),
            new Tower('qvcnscn', 21),
            new Tower('pkyos', 67),
            new Tower('teduvz', 61, ['watknc', 'ibvain']),
            new Tower('oppaock', 53),
            new Tower('vrlcw', 823, ['svibl', 'upxfo', 'kzxpedk']),
            new Tower('rmwhlgz', 179, ['zjkdtrq', 'jpshwm', 'dytikd']),
            new Tower('qjpyu', 191, ['ssnkl', 'cqakc', 'mentp']),
            new Tower('cxrjgg', 25),
            new Tower('btmuz', 154, ['pnxkdii', 'fxhtvj']),
            new Tower('ithtabv', 50),
            new Tower('hjbghmi', 45),
            new Tower('yxlqjxz', 61),
            new Tower('huwrhd', 92),
            new Tower('xgzmr', 471, ['yiwuei', 'kdptwot', 'wjkdl', 'ialdmz', 'nqkbjlh', 'lkijuws']),
            new Tower('iebero', 287, ['honhsr', 'cehuzkr']),
            new Tower('cqgqm', 214, ['ryatef', 'khuyb', 'opluk']),
            new Tower('njiwy', 19),
            new Tower('nqkbjlh', 237, ['xhifoak', 'nkikn']),
            new Tower('wjaav', 94),
            new Tower('gtmfflw', 13, ['cnsemxt', 'tdmre', 'wqcyyp']),
            new Tower('gxfqm', 9),
            new Tower('jccqeca', 60, ['yxzvg', 'hsedh']),
            new Tower('jvmpc', 180, ['oiuih', 'yeojp']),
            new Tower('gzogp', 9, ['tzhjol', 'xwuvr', 'tjurw', 'fnecqcx', 'hovodbo', 'mjorwvu']),
            new Tower('phkhvmp', 127, ['tmicb', 'kfnox', 'xuxtbe', 'qzflerr']),
            new Tower('jirvayi', 84),
            new Tower('vsuyxah', 68),
            new Tower('uzcfn', 11),
            new Tower('jxuvy', 128, ['nplxpml', 'wttkrli']),
            new Tower('ihmflgt', 39),
            new Tower('efwsj', 13),
            new Tower('ntdeykb', 11),
            new Tower('kolxt', 195, ['sctwwty', 'esxbml']),
            new Tower('viofo', 72),
            new Tower('svugo', 32, ['xolvnpy', 'gjxqx', 'gtzxxav', 'njorjq', 'qpiklvf']),
            new Tower('owjht', 58),
            new Tower('sfjspc', 41, ['jlzxun', 'gnweaxi', 'ftloq', 'xbqsegw']),
            new Tower('bmfcc', 48, ['ixmsn', 'sdosxki', 'pmwsup']),
            new Tower('bqrvhzi', 21),
            new Tower('yemke', 49, ['hqdcn', 'jltou', 'fnjdau', 'lwemj', 'eathpcv', 'xwslnr']),
            new Tower('pmwzrxm', 103, ['mumtfo', 'azokid', 'cueuqa']),
            new Tower('vnqxpf', 30),
            new Tower('rkait', 96),
            new Tower('rtsbu', 120, ['isnkzg', 'ipmyklq']),
            new Tower('tmxbh', 363),
            new Tower('jfctkmt', 60),
            new Tower('ihsfpwk', 19),
            new Tower('lhdgv', 59),
            new Tower('syefk', 45),
            new Tower('aglcugi', 368, ['iaybgca', 'fekljc', 'pxhroue']),
            new Tower('mezpvo', 47),
            new Tower('olaxe', 36),
            new Tower('gpudbvp', 33),
            new Tower('mrzmkae', 91),
            new Tower('neoyxft', 11),
            new Tower('rpdrdxo', 77),
            new Tower('spxqd', 24),
            new Tower('pjkrgv', 64),
            new Tower('gcashr', 16),
            new Tower('ohfpwd', 42),
            new Tower('dvkjfk', 310),
            new Tower('fzmzcc', 137, ['rzgdz', 'bptimbu']),
            new Tower('nithd', 47),
            new Tower('wttkrli', 60),
            new Tower('kyoopc', 167, ['ntdeykb', 'uzcfn']),
            new Tower('vyitr', 23),
            new Tower('gggvdzp', 65, ['fxjacfb', 'gxwqiat', 'trotdqj', 'ygvnuu']),
            new Tower('nikpljz', 97),
            new Tower('xolvnpy', 22946, ['dfbeg', 'ajrrm', 'niuzt']),
            new Tower('zkyvs', 76),
            new Tower('qkyqkf', 38),
            new Tower('wdprouh', 69),
            new Tower('mtpicwi', 162, ['lzkcsih', 'hlcpmj', 'lzllws']),
            new Tower('vdvwz', 92),
            new Tower('nplxpml', 60),
            new Tower('spagr', 200, ['fkzarsq', 'awweagx']),
            new Tower('uezwbls', 92),
            new Tower('wqmlfzf', 98),
            new Tower('qubsj', 176, ['agnkj', 'ewbgxj']),
            new Tower('rpijm', 71, ['cjszhjz', 'cbihaff']),
            new Tower('udwhf', 1047, ['kolxt', 'trwpih', 'oqhuqw', 'jggkrpf']),
            new Tower('oebjoin', 18),
            new Tower('zhfpuu', 88),
            new Tower('uyeeefd', 55),
            new Tower('asckjlv', 4889, ['majzil', 'mubtpc', 'wgufuoj', 'uxlfqru']),
            new Tower('uvokiil', 18),
            new Tower('lybou', 114, ['bsttxpj', 'ivbkm']),
            new Tower('pmutbr', 18),
            new Tower('ipmyklq', 28),
            new Tower('gjxqx', 14, ['yruivis', 'rizjob', 'qsfwl', 'asckjlv', 'sfqwrge', 'bncdhrm']),
            new Tower('essizn', 185, ['tdreqt', 'ycoeh']),
            new Tower('wcvuu', 57),
            new Tower('wwdta', 85, ['mdpdynj', 'fdvks', 'zyufjm']),
            new Tower('vjjvitk', 30),
            new Tower('frgpbr', 21),
            new Tower('vkvsku', 59),
            new Tower('dcdgsj', 81),
            new Tower('ursswr', 50),
            new Tower('pasahyc', 31, ['tvuey', 'yosexh']),
            new Tower('nstfuaj', 82),
            new Tower('lbogwls', 82),
            new Tower('zzsjca', 15, ['sglbby', 'bkxbja']),
            new Tower('oxipms', 2533, ['njfaf', 'okyya']),
            new Tower('oegjhcg', 196, ['tbplngl', 'kcqxplp']),
            new Tower('qgwyq', 292, ['odqodqo', 'tuuzkn']),
            new Tower('qqckql', 88),
            new Tower('hnlec', 30),
            new Tower('lwaoy', 89),
            new Tower('pjcluy', 32),
            new Tower('wgfbd', 68),
            new Tower('rzqtfk', 167, ['nggfesp', 'jmnzios', 'iecbxj', 'gijrym']),
            new Tower('kmmtdma', 68),
            new Tower('jvkpk', 14),
            new Tower('cedfch', 94),
            new Tower('rbpdfud', 138, ['wqmlfzf', 'meyihxo']),
            new Tower('rlcbfav', 960, ['yqjtia', 'qycgu', 'jzpih']),
            new Tower('shscp', 146, ['zjovf', 'rwjupwq']),
            new Tower('remft', 188, ['yevgrf', 'mzvna']),
            new Tower('lwwovy', 34),
            new Tower('douxy', 391, ['ayqfub', 'pwgtgs', 'voqlc', 'xfcaona', 'inilfk']),
            new Tower('guaulxm', 92),
            new Tower('fciapx', 153, ['hnlec', 'xlvzg', 'yjxiv']),
            new Tower('bbozoqx', 98),
            new Tower('rgicvct', 57),
            new Tower('cyusmf', 904, ['rhazko', 'imrtnt']),
            new Tower('ebyaofj', 169, ['wudjb', 'uyjoabs']),
            new Tower('xkdkyxu', 92),
            new Tower('sorhq', 198),
            new Tower('ymetxqm', 21),
            new Tower('cbihaff', 19),
            new Tower('kuzim', 130, ['vcbcy', 'mzozybe']),
            new Tower('gehri', 45, ['uikxbgu', 'zotzrjn']),
            new Tower('ebvlur', 31),
            new Tower('wormisx', 75),
            new Tower('tcnrrg', 83),
            new Tower('mdpwa', 76),
            new Tower('honhsr', 27),
            new Tower('qpiklvf', 11870, ['weohqnq', 'oifwih', 'udamz']),
            new Tower('mjtsrs', 153, ['pexdlf', 'sjrepyz']),
            new Tower('mcqnk', 18),
            new Tower('zunzpwe', 61),
            new Tower('hsedh', 94),
            new Tower('blrgxsb', 13),
            new Tower('khvwq', 93),
            new Tower('zrprsn', 370, ['tqwxt', 'eshhfd', 'jrqnj']),
            new Tower('gxlrkmy', 93),
            new Tower('mmcebdy', 37),
            new Tower('ovlnitv', 6),
            new Tower('dkzlr', 38),
            new Tower('hrjop', 74, ['brtxkgi', 'vgdjxl']),
            new Tower('efcjat', 78),
            new Tower('ymjmo', 22),
            new Tower('gnweaxi', 44),
            new Tower('fbplv', 90),
            new Tower('ttldnhl', 8265, ['qifwjr', 'qckol', 'qjpyu', 'cyusmf', 'aglcugi', 'bkkwt']),
            new Tower('mwkjo', 206, ['kgfbft', 'eqlnvl', 'uihrkc']),
            new Tower('fuitrtz', 89),
            new Tower('vpuxpxj', 165, ['bkuxrk', 'lqxevih', 'eixwwxn']),
            new Tower('onrklke', 20),
            new Tower('cirsfs', 182, ['adckzt', 'ujgeo']),
            new Tower('emqnw', 55),
            new Tower('ysseykl', 88, ['noxvqga', 'pmlho', 'cdlnovn']),
            new Tower('yluell', 270),
            new Tower('njfaf', 69),
            new Tower('ydtqhd', 174, ['fpmzgvo', 'ibasy', 'zoeam', 'bpboa']),
            new Tower('noybkx', 21),
            new Tower('hkcuz', 126, ['vefasv', 'cvbnb']),
            new Tower('jcjsn', 15),
            new Tower('xxikrr', 14),
            new Tower('jxcxf', 14),
            new Tower('wleja', 43),
            new Tower('oyegdcw', 27),
            new Tower('lqdyln', 78),
            new Tower('ngpkzb', 92),
            new Tower('axsupxp', 861, ['bpcxrn', 'jjhqu', 'fvtboh', 'emgpu']),
            new Tower('gnovsx', 38),
            new Tower('kizgz', 38),
            new Tower('leubrjl', 41),
            new Tower('eflhino', 370, ['qubsj', 'cqgqm', 'ftcizt', 'lkuphpg', 'tcndbu']),
            new Tower('xlvzg', 30),
            new Tower('xbqsegw', 44),
            new Tower('xbbygk', 22),
            new Tower('rujpx', 44),
            new Tower('inzafdy', 23),
            new Tower('hnurp', 294, ['aaspu', 'ncrzjm']),
            new Tower('cvbnb', 32),
            new Tower('cxuzdyf', 180, ['hvfav', 'lnund']),
            new Tower('xewgja', 310),
            new Tower('muarank', 260, ['yvzuohq', 'ecbpy']),
            new Tower('pucapcr', 35),
            new Tower('tpldx', 119, ['fyqftv', 'ttiemo', 'vjjvitk', 'xgzja']),
            new Tower('hnszth', 13),
            new Tower('uajyksv', 7, ['avlhpbs', 'ywzku']),
            new Tower('yuecj', 6),
            new Tower('jdgbrz', 79),
            new Tower('cofol', 1327, ['zjkxmfh', 'xniyrk', 'bqzcmr', 'gjaltuo', 'oapztg']),
            new Tower('tkvcp', 111, ['jpfbl', 'dmoexuj', 'vopoojk', 'blebnht']),
            new Tower('bbmmtud', 186, ['qvcnscn', 'pomeveh', 'mflxo']),
            new Tower('lcggy', 77),
            new Tower('dytikd', 8),
            new Tower('tqwxt', 5),
            new Tower('hthizhf', 12),
            new Tower('zmfeb', 96),
            new Tower('uaajucq', 174, ['khuqo', 'onnwjy', 'nmpojs', 'jzhtpli']),
            new Tower('gppcfr', 95),
            new Tower('oswptur', 15),
            new Tower('tculi', 344),
            new Tower('anvukkl', 29),
            new Tower('zksug', 25),
            new Tower('luemof', 68),
            new Tower('onnwjy', 15),
            new Tower('eqlnvl', 44),
            new Tower('ywzku', 91),
            new Tower('amulani', 85, ['kedwhhj', 'stjjr']),
            new Tower('wxikdvk', 29),
            new Tower('lkhbcfn', 97),
            new Tower('cueuqa', 69),
            new Tower('fzwdnl', 139, ['thbbk', 'kmecjf', 'mjverr', 'oswptur']),
            new Tower('bpjtor', 125, ['twcrr', 'ltiabeu', 'vlbxwof', 'lycxba']),
            new Tower('emszr', 36),
            new Tower('lcxllj', 59),
            new Tower('ihbeh', 34),
            new Tower('qjqyd', 48),
            new Tower('nggfesp', 18),
            new Tower('ugres', 102),
            new Tower('kkxxua', 34),
            new Tower('hjwyc', 28),
            new Tower('meygo', 37),
            new Tower('twcrr', 63),
            new Tower('trwpih', 297, ['hghnmv', 'nzygm']),
            new Tower('sphbbz', 1161, ['gioryg', 'scetry', 'sfjspc', 'ivpbt', 'vyufo', 'valbm', 'oprfjt']),
            new Tower('dzhvos', 51, ['nithd', 'dleprko', 'hqvbm', 'bcmtnt']),
            new Tower('drxxrz', 12),
            new Tower('igjcv', 21),
            new Tower('ubwfyx', 35),
            new Tower('xtuocx', 42),
            new Tower('kepgi', 7, ['ndfkl', 'lsxavn']),
            new Tower('ujgeo', 24),
            new Tower('cjusyky', 12),
            new Tower('ijlsc', 35),
            new Tower('myhzuy', 67),
            new Tower('fkzarsq', 26),
            new Tower('tdmre', 66),
            new Tower('xponr', 68),
            new Tower('hrhwxq', 23),
            new Tower('vhfqi', 49),
            new Tower('dyhtgng', 302, ['wngrd', 'covjpf', 'mosbw', 'ljvrj', 'jvegmwc', 'mptzfm']),
            new Tower('scetry', 9, ['qvzlvq', 'eounj', 'iaibv', 'zkhxn']),
            new Tower('ivbkm', 56),
            new Tower('rwjupwq', 43),
            new Tower('sxppnu', 4079, ['tisslxr', 'hqvoym', 'ahdgqpm', 'xpmraw', 'dghbo']),
            new Tower('zxpxr', 35),
            new Tower('lnund', 98),
            new Tower('bpcxrn', 146, ['poslxf', 'ryclgvc', 'vgdjz']),
            new Tower('uxlfqru', 643, ['mhxpay', 'taslihw', 'ttqrjz']),
            new Tower('bcmtnt', 47),
            new Tower('iodopqk', 610, ['zhffwjr', 'sykqu', 'btmuz', 'cirsfs']),
            new Tower('gbmobi', 97),
            new Tower('xutqsde', 18),
            new Tower('opyjeyu', 79),
            new Tower('ydwug', 112, ['fbplv', 'clvvt', 'pnyyag']),
            new Tower('aemufzz', 246, ['tatyvy', 'rujpx']),
            new Tower('dkasko', 86, ['nstfuaj', 'vmcib']),
            new Tower('xgytt', 377),
            new Tower('zjurdqp', 115, ['adooxhb', 'meygo']),
            new Tower('jpfbl', 52),
            new Tower('ebjlbr', 112),
            new Tower('rhazko', 20),
            new Tower('ajrrm', 7311, ['yemke', 'ugmfrt', 'crnvz']),
            new Tower('zrltc', 183, ['jdenl', 'anvukkl', 'wxikdvk']),
            new Tower('urliam', 69),
            new Tower('nwjosw', 198, ['iilxm', 'cvmjs', 'jgzuz']),
            new Tower('mavpqd', 367, ['ymetxqm', 'izdutmt', 'ptvkpk']),
            new Tower('vbsku', 35),
            new Tower('ljvrj', 183, ['drxxrz', 'ueheft']),
            new Tower('jrqnj', 5),
            new Tower('biibrbq', 6792, ['gzogp', 'udwhf', 'vfepai']),
            new Tower('escjt', 82),
            new Tower('zokte', 31),
            new Tower('psjyx', 46),
            new Tower('ysqizk', 22),
            new Tower('ihxtg', 41),
            new Tower('jzpih', 127, ['igjcv', 'gvbxg', 'umkwa']),
            new Tower('rqswk', 189, ['ohfpwd', 'usdonaj']),
            new Tower('llsqcnz', 23),
            new Tower('mosbw', 21, ['tenewcj', 'losxko']),
            new Tower('ukvdvgo', 78),
            new Tower('jlzxun', 44),
            new Tower('wounsqk', 99),
            new Tower('arsrlmc', 66, ['putprdw', 'pgfgtwj']),
            new Tower('hxnea', 302, ['gcashr', 'wwmta']),
            new Tower('pxhroue', 98, ['diccfps', 'mezpvo']),
            new Tower('mmgep', 155, ['yscvt', 'vdxvll']),
            new Tower('lsgvik', 65, ['jgqxt', 'yztcfw', 'jmnxhqh']),
            new Tower('wjkdl', 179, ['rwtyr', 'zxpxr']),
            new Tower('yfkfk', 90, ['xvtvomy', 'pkktbxs']),
            new Tower('tucemlh', 82),
            new Tower('zsvyve', 2401, ['lokxju', 'oppaock']),
            new Tower('gvbxg', 21),
            new Tower('izdutmt', 21),
            new Tower('dutfal', 59),
            new Tower('qqlkwr', 59),
            new Tower('pmwsup', 74),
            new Tower('xgzja', 30),
            new Tower('epflhcq', 314, ['pxqgvjs', 'ebvlur']),
            new Tower('snqyc', 90),
            new Tower('jgzuz', 13),
            new Tower('poslxf', 73),
            new Tower('wfzkd', 6),
            new Tower('kbcjy', 81),
            new Tower('fnecqcx', 231, ['yuerovj', 'kbcztr']),
            new Tower('wgmxwy', 78, ['kysof', 'zrqkic', 'qytnj', 'qqvrhv']),
            new Tower('ezwrgwg', 23),
            new Tower('fteop', 38),
            new Tower('qimvddh', 99, ['qjqyd', 'iyytgk', 'ppepf']),
            new Tower('lycxba', 63),
            new Tower('cjszhjz', 19),
            new Tower('nbksews', 75, ['fpdttlv', 'ygjbwu', 'vlhrcsh', 'sdawsdp', 'lzzeke']),
            new Tower('sfqwrge', 948, ['pdyhl', 'njzaj', 'uaztc', 'hpthw', 'xgzmr']),
            new Tower('upxfo', 204, ['akqoae', 'fgihxex']),
            new Tower('wterb', 93),
            new Tower('nxvhzm', 75),
            new Tower('xrffbj', 88),
            new Tower('jpshwm', 8),
            new Tower('imnmqmc', 1056, ['crghfz', 'rsygg', 'fpimfx', 'icurk', 'infjgg', 'drxkj']),
            new Tower('errywn', 2003, ['jklwqzz', 'blzatj', 'uiqegu']),
            new Tower('bqgxg', 14),
            new Tower('iollvjh', 75),
            new Tower('bwtwoy', 46),
            new Tower('khaneu', 35, ['spuzkk', 'sheuujc']),
            new Tower('aaspu', 41),
            new Tower('nzmzrf', 63),
            new Tower('etgpwm', 22),
            new Tower('kwilox', 41, ['cedfch', 'wjaav']),
            new Tower('asefoiu', 249),
            new Tower('sglbby', 94),
            new Tower('mnchjf', 65, ['cimsvsq', 'grmps']),
            new Tower('lzllws', 90),
            new Tower('kvmxpmx', 93),
            new Tower('ectqv', 37, ['rmbnnq', 'fuvary']),
            new Tower('amauas', 34),
            new Tower('gymdygg', 26, ['zmpsuwb', 'wonxy', 'lqdyln', 'efcjat']),
            new Tower('tzespqz', 56),
            new Tower('rkotan', 72, ['gumtctd', 'snqyc']),
            new Tower('chtiq', 89),
            new Tower('oflkits', 88),
            new Tower('zjpzq', 94, ['bskomwv', 'ythizc', 'pucapcr', 'ubwfyx']),
            new Tower('rbozm', 214, ['qzxsz', 'qvily']),
            new Tower('otgvzj', 194, ['sygrs', 'gxlrkmy']),
            new Tower('jzhtpli', 15),
            new Tower('tfdwxe', 89),
            new Tower('ialdmz', 12, ['gznay', 'jdgbrz', 'tcvrov']),
            new Tower('dleprko', 47),
            new Tower('kgfbft', 44),
            new Tower('iyytgk', 48),
            new Tower('jcjqr', 99),
            new Tower('smlnw', 376),
            new Tower('uqork', 26),
            new Tower('hduix', 55),
            new Tower('sbbpewr', 64, ['nkohugb', 'qfrgkwt']),
            new Tower('njpyn', 834, ['npqwie', 'sbbpewr', 'nvqjado']),
            new Tower('mhhfovk', 1721, ['camcas', 'fzwdnl', 'ujacw']),
            new Tower('wmskqd', 31),
            new Tower('bpboa', 44),
            new Tower('udamz', 45, ['sitbr', 'cofol', 'zsvyve', 'errywn', 'sizeg', 'thqkly', 'ccqhl']),
            new Tower('wfsovdl', 47),
            new Tower('jzlmges', 237),
            new Tower('dnacpie', 61, ['ngadrj', 'gedohd', 'yuvmlq', 'klmedvh', 'aende', 'tkvcp']),
            new Tower('fdoszd', 97),
            new Tower('ajkxrcl', 71, ['ykbvkc', 'escjt', 'yolrl', 'kuoluj']),
            new Tower('kiqjb', 89, ['whiwt', 'bdkcdaq']),
            new Tower('yqgwle', 31),
            new Tower('wnykty', 53),
            new Tower('kfnox', 21),
            new Tower('khuyb', 6),
            new Tower('fljico', 212),
            new Tower('vzhdg', 78),
            new Tower('qqqxi', 88),
            new Tower('tmnklf', 982, ['hxnea', 'wwdta', 'aemufzz', 'rbpdfud']),
            new Tower('axnnpf', 73),
            new Tower('ijcvtep', 41),
            new Tower('ihcolp', 70),
            new Tower('vefasv', 32),
            new Tower('pruqcvk', 34),
            new Tower('agnkj', 28),
            new Tower('fuxnvo', 33, ['ngpkzb', 'xkdkyxu']),
            new Tower('ejqqxk', 75),
            new Tower('afzkp', 83),
            new Tower('prssjgo', 13),
            new Tower('rzgdz', 46),
            new Tower('pzxqe', 139, ['zokte', 'wmskqd']),
            new Tower('cmgfqkb', 48),
            new Tower('xwdlxg', 178, ['qpfup', 'wnykty', 'vwlcnv', 'vjzph']),
            new Tower('sizeg', 2371, ['lwwovy', 'amauas', 'krcdkw', 'kkxxua']),
            new Tower('lnhrx', 258, ['isceom', 'bwtwoy']),
            new Tower('mentp', 185, ['gpudbvp', 'ljvipn']),
            new Tower('njimb', 15),
            new Tower('hxzqgfl', 76),
            new Tower('giagung', 52),
            new Tower('qzxsz', 7),
            new Tower('egbjx', 84),
            new Tower('zrqkic', 28),
            new Tower('kzwcue', 81),
            new Tower('iilxm', 13),
            new Tower('qckol', 416, ['mnkholz', 'hrobopm', 'rtsbu']),
            new Tower('tzhjol', 278, ['ihmflgt', 'jvnks', 'iefgdb']),
            new Tower('ecbpy', 85),
            new Tower('okyya', 69),
            new Tower('aealnl', 63),
            new Tower('gnetslx', 58),
            new Tower('jvaqkq', 56, ['xgytt', 'mkwoc', 'mtwvvup', 'cbodyg', 'llajkfm', 'bpjtor']),
            new Tower('mfgpyyw', 47),
            new Tower('pohvscs', 81),
            new Tower('nmawxdq', 35),
            new Tower('xhtorci', 46),
            new Tower('wajjyev', 119, ['mmkbh', 'lcggy']),
            new Tower('bdovfqj', 60),
            new Tower('klmedvh', 319),
            new Tower('ercgkci', 81),
            new Tower('vdcnit', 214, ['zxiqpq', 'oflkits']),
            new Tower('vvqpt', 66),
            new Tower('nqwkb', 98),
            new Tower('hqdcn', 205, ['wiwrw', 'jgnvooj', 'wtsgud']),
            new Tower('fbhzkoh', 32, ['afzkp', 'knbeerh']),
            new Tower('sgygf', 50),
            new Tower('aklxi', 211, ['pvrocec', 'lstxl']),
            new Tower('dfbeg', 77, ['dnacpie', 'xgjyuie', 'ygnxu', 'gpsaq', 'vrlcw', 'xnzmf', 'tongu']),
            new Tower('jltou', 358),
            new Tower('ptvkpk', 21),
            new Tower('camcas', 129, ['qubakh', 'tromme']),
            new Tower('iunpq', 1373, ['ruusx', 'hrjop', 'lybou']),
            new Tower('eounj', 52),
            new Tower('oiuih', 85),
            new Tower('uiakb', 28),
            new Tower('imrtnt', 20),
            new Tower('ylzdc', 57),
            new Tower('chsgrkx', 90),
            new Tower('vgdjz', 73),
            new Tower('nnbcnzu', 1184, ['pedrwzo', 'unkckgx', 'sklzg']),
            new Tower('bhgcvz', 50),
            new Tower('wtioxkx', 90, ['fgoqtbj', 'zunzpwe', 'yxlqjxz']),
            new Tower('fvtboh', 68, ['hrwcuqh', 'wjccpg', 'wounsqk']),
            new Tower('thqkly', 1735, ['krldk', 'gdndx', 'mmgep', 'qwrruob']),
            new Tower('cqcqid', 21),
            new Tower('buaue', 1110, ['arpzsz', 'ueyxaa', 'iowckgn']),
            new Tower('gwqvxp', 38),
            new Tower('ukjzi', 26),
            new Tower('jdooxot', 158, ['zkbdn', 'tshems']),
            new Tower('vjxqtpi', 95),
            new Tower('zyufjm', 83),
            new Tower('vlhrcsh', 139, ['gnovsx', 'zwpqdpp', 'qkyqkf', 'hhgrgoa']),
            new Tower('gftxf', 79),
            new Tower('vywee', 45),
            new Tower('wlrdp', 58),
            new Tower('eebyw', 84),
            new Tower('cafcfnl', 19, ['ntnqvtk', 'uezwbls']),
            new Tower('ogltzt', 12),
            new Tower('saifkw', 11, ['rkait', 'srozw']),
            new Tower('ruusx', 28, ['jcjqr', 'bchpnd']),
            new Tower('ndfkl', 91),
            new Tower('brjpqy', 168, ['zfusug', 'uagtgt', 'htzdq']),
            new Tower('zmpsuwb', 78),
            new Tower('sklzg', 63, ['wvrrwfs', 'kpnjwzl', 'gftxf', 'unrxrxg']),
            new Tower('mhmbmve', 75),
            new Tower('jhztf', 93),
            new Tower('rdiysu', 18),
            new Tower('yuvmlq', 229, ['cadkdj', 'syefk']),
            new Tower('scurl', 906, ['oymgkey', 'otgvzj', 'dojoi']),
            new Tower('kdkng', 23),
            new Tower('akqoae', 90),
            new Tower('nigxeuz', 18),
            new Tower('pwgtgs', 194, ['ykiurcc', 'mapgeoe']),
            new Tower('vgdjxl', 76),
            new Tower('sgbzm', 108, ['wwutk', 'licetbw', 'nwjosw', 'jzlmges', 'qlfars', 'gggvdzp']),
            new Tower('julhx', 72),
            new Tower('lfbbsay', 63),
            new Tower('iaybgca', 129, ['frgpbr', 'mvqoekw', 'vmebh']),
            new Tower('tunuzcn', 17, ['nquzdn', 'qzohrj', 'rsmvde', 'thsdq']),
            new Tower('tbtzwz', 153, ['wleja', 'pckcqy']),
            new Tower('vxrdwe', 15),
            new Tower('fzuomz', 27),
            new Tower('uyjoabs', 37),
            new Tower('imcujsr', 92, ['bdovfqj', 'tnmziio']),
            new Tower('bipgvd', 173, ['nmawxdq', 'tbnuh']),
            new Tower('mubtpc', 85, ['juifyyw', 'uxpblf', 'sqbnfxf']),
            new Tower('ghhfd', 60),
            new Tower('noxvqga', 98),
            new Tower('wwutk', 127, ['mbxchx', 'tmybiz']),
            new Tower('njorjq', 31504, ['ppgcgz', 'tdqqjpg', 'zuhfs', 'lyxqyl']),
            new Tower('tzypui', 85),
            new Tower('oopqud', 261, ['lxkwe', 'urvedm']),
            new Tower('rklqa', 59, ['nwsecpl', 'xtnyr']),
            new Tower('pnyyag', 90),
            new Tower('igaui', 84),
            new Tower('thbbk', 15),
            new Tower('unrxrxg', 79),
            new Tower('gcdbb', 74),
            new Tower('urgfd', 48),
            new Tower('srwgf', 31),
            new Tower('phmpasy', 18),
            new Tower('kcqndc', 60),
            new Tower('faendwk', 83, ['kcqndc', 'jfctkmt']),
            new Tower('rizjob', 6366, ['eknipd', 'mhhvcg', 'zparvpi']),
            new Tower('aaalewd', 95),
            new Tower('mzymfht', 22),
            new Tower('silwij', 75),
            new Tower('xtnyr', 90),
            new Tower('lxkwe', 6),
            new Tower('nquzdn', 46),
            new Tower('szyzmuw', 28),
            new Tower('kkidtmk', 13),
            new Tower('bxeil', 81),
            new Tower('bsttxpj', 56),
            new Tower('jhpiym', 94),
            new Tower('zjkxmfh', 236),
            new Tower('sultgf', 90, ['uyeeefd', 'hduix', 'zrofm', 'zqdnix']),
            new Tower('hturdef', 24),
            new Tower('jimcygz', 75),
            new Tower('xlxroru', 6),
            new Tower('nlirga', 41),
            new Tower('ypxvo', 40, ['nqwkb', 'bbozoqx', 'jvwlo', 'yktkkr']),
            new Tower('wudjb', 37),
            new Tower('blebnht', 52),
            new Tower('bkkwt', 335, ['khaneu', 'zzsjca', 'rmwhlgz']),
            new Tower('pdqvd', 64),
            new Tower('whiwt', 64),
            new Tower('jiqrrq', 35),
            new Tower('tbjbz', 93),
            new Tower('pedrwzo', 309, ['zwjdka', 'jiqrrq']),
            new Tower('zoeam', 44),
            new Tower('rmqmme', 97),
            new Tower('awfrk', 25),
            new Tower('majzil', 784, ['fzmzcc', 'bnawjt', 'kwilox']),
            new Tower('qsfwl', 63, ['rlcbfav', 'iodopqk', 'njpyn', 'kwymyn', 'sgbzm', 'nbksews', 'eflhino']),
            new Tower('bnawjt', 137, ['hrhwxq', 'ybtsie', 'inzafdy', 'ezwrgwg']),
            new Tower('usdonaj', 42),
            new Tower('mjvxc', 188, ['wyiofd', 'sgygf', 'ursswr']),
            new Tower('yefht', 196, ['xutqsde', 'pmutbr']),
            new Tower('smhctr', 38),
            new Tower('qsnwd', 65, ['cxuzdyf', 'qtgxg', 'smlnw', 'hnurp', 'epflhcq', 'kixuhs']),
            new Tower('cjixx', 241, ['wdprouh', 'urliam']),
            new Tower('zdtby', 961, ['dtfayu', 'qfuqfre', 'yaqfv', 'fuxnvo', 'kiqjb']),
            new Tower('iovig', 22),
            new Tower('zrofm', 55),
            new Tower('dybapm', 159, ['jtxkj', 'utnwfrl', 'cdzfql', 'emqnw']),
            new Tower('qtgxg', 376),
            new Tower('oxpphmz', 1319, ['uylmxqo', 'hufovxb', 'ugres']),
            new Tower('uzpxmf', 198),
            new Tower('vchfk', 23),
            new Tower('fvcbh', 233, ['xsauoti', 'joruazf', 'ijlsc']),
            new Tower('xvmstn', 64),
            new Tower('nvxbdd', 6),
            new Tower('zauos', 107, ['uniifn', 'xponr']),
            new Tower('yvzuohq', 85),
            new Tower('kvqrdbr', 15),
            new Tower('uikxbgu', 97),
            new Tower('wgufuoj', 667, ['ovzoej', 'pzxqe', 'pasahyc', 'tunuzcn']),
            new Tower('ecsdihr', 93),
            new Tower('kyvqypb', 16),
            new Tower('eathpcv', 256, ['tugui', 'psdcdbm']),
            new Tower('iclrood', 121, ['vyitr', 'qynklua', 'aahmp']),
            new Tower('uiycup', 59),
            new Tower('ttiemo', 30),
            new Tower('zhffwjr', 89, ['casskdk', 'wfsovdl', 'umzrb']),
            new Tower('jddjjw', 21, ['jvaqkq', 'mhhfovk', 'flsxmc', 'tmnklf', 'lazvv', 'cfxwzf']),
            new Tower('yvicgh', 73),
            new Tower('hrwcuqh', 99),
            new Tower('yypsdby', 41),
            new Tower('sgnexg', 96),
            new Tower('xxdnojb', 92),
            new Tower('mbymo', 81),
            new Tower('bwujye', 83),
            new Tower('covjpf', 61, ['qiediji', 'yvicgh']),
            new Tower('xxelf', 34),
            new Tower('juihbkt', 94),
            new Tower('gludbju', 12),
            new Tower('oqhuqw', 90, ['ercgkci', 'ogrpc', 'bxeil']),
            new Tower('bqzcmr', 108, ['pjkrgv', 'rfooa']),
            new Tower('mumtfo', 69),
            new Tower('dpbywy', 49),
            new Tower('fpimfx', 119, ['skgciiy', 'cqlnevp']),
            new Tower('ygnxu', 160, ['bpctu', 'siykhg', 'aklxi', 'brjpqy', 'tmxbh']),
            new Tower('tcvrov', 79),
            new Tower('zncyr', 999, ['ezxakj', 'injvyeb', 'whboh']),
            new Tower('qzflerr', 21),
            new Tower('enjhfeg', 13),
            new Tower('eixwwxn', 29),
            new Tower('ryatef', 6),
            new Tower('bkxbja', 94),
            new Tower('eeuykqk', 47),
            new Tower('ivinyhh', 6),
            new Tower('swshl', 25),
            new Tower('mapgeoe', 69),
            new Tower('jljjh', 37),
            new Tower('fuvary', 75),
            new Tower('njbqsh', 33),
            new Tower('ztfziz', 56, ['nikpljz', 'gbmobi']),
            new Tower('kikqp', 97),
            new Tower('uwmpw', 97),
            new Tower('hqvoym', 1226, ['jccqeca', 'xbeau', 'jxuvy']),
            new Tower('isnkzg', 28),
            new Tower('wsstaru', 12),
            new Tower('edsdrz', 59),
            new Tower('sqbnfxf', 440, ['guuvcz', 'wniti']),
            new Tower('sviek', 24),
            new Tower('cmdjxza', 76),
            new Tower('putprdw', 73),
            new Tower('dnrtq', 72),
            new Tower('cuvpk', 97),
            new Tower('qghnwdf', 94, ['jirvayi', 'eebyw', 'igaui', 'nklype']),
            new Tower('gffoyh', 91),
            new Tower('wumlot', 221, ['neoyxft', 'cinjgkc']),
            new Tower('rfooa', 64),
            new Tower('yevgrf', 32),
            new Tower('pkuggs', 131, ['fdplo', 'tzespqz']),
            new Tower('vaexiu', 1581, ['ymjmo', 'iovig']),
            new Tower('rehpie', 86, ['liori', 'zauos', 'ebyaofj', 'pbqrv', 'fciapx', 'bipgvd']),
            new Tower('vcumw', 94),
            new Tower('uobgk', 338, ['adygspa', 'psjyx']),
            new Tower('gtvsym', 18),
            new Tower('wvrrwfs', 79),
            new Tower('pckcqy', 43),
            new Tower('qymuwz', 74),
            new Tower('cfxwzf', 1634, ['mlvywui', 'kuzim', 'rbozm']),
            new Tower('hrwhc', 51, ['jhpiym', 'juihbkt']),
            new Tower('lazvv', 1589, ['pkuggs', 'wumlot', 'qimvddh']),
            new Tower('ykbvkc', 82),
            new Tower('tbplngl', 18),
            new Tower('sjrepyz', 60),
            new Tower('tdreqt', 54),
            new Tower('jvlrpy', 7),
            new Tower('zwrwngq', 203),
            new Tower('valbm', 65, ['cmdjxza', 'tzcosab']),
            new Tower('zfkfc', 856, ['tbtzwz', 'dzhvos', 'tcewj', 'gehri', 'ixcueuk']),
            new Tower('qrncpfb', 463, ['trrrswp', 'mjtsrs', 'ziiojfl']),
            new Tower('hsnkmd', 77),
            new Tower('ttqrjz', 86, ['ddmyid', 'gppcfr']),
            new Tower('lnddtya', 60),
            new Tower('ghzfclb', 929, ['aokguyj', 'shscp', 'zzjap']),
            new Tower('cvmjs', 13),
            new Tower('tongu', 778, ['ajkxrcl', 'hjsyte', 'mhtgqj']),
            new Tower('amwlt', 102, ['putxfkb', 'edswm']),
            new Tower('ixcueuk', 181, ['kgjzt', 'qxnfz']),
            new Tower('jvnks', 39),
            new Tower('kzxpedk', 72, ['udiibbj', 'izvxax', 'ymnqdi', 'ukvdvgo']),
            new Tower('jmnzios', 18),
            new Tower('aglfaj', 78),
            new Tower('qqfxsbl', 56),
            new Tower('omivhf', 24),
            new Tower('mkjdh', 62, ['zksug', 'squxhq']),
            new Tower('ogilk', 28),
            new Tower('drxkj', 39, ['atjgje', 'lfbbsay']),
            new Tower('lcltlz', 90, ['dmobhqz', 'lelwu']),
            new Tower('exyceo', 81),
            new Tower('paguj', 212, ['njiwy', 'ihsfpwk']),
            new Tower('odqodqo', 70),
            new Tower('umzrb', 47),
            new Tower('yosexh', 85),
            new Tower('bchpnd', 99),
            new Tower('wngrd', 115, ['fpzvpx', 'xhtorci']),
            new Tower('hjlabl', 56),
            new Tower('nrqmk', 35),
            new Tower('kdptwot', 195, ['gtvsym', 'svmplb', 'pnbyuu']),
            new Tower('injvyeb', 112),
            new Tower('llajkfm', 277, ['bhgcvz', 'cpjwxir']),
            new Tower('cbodyg', 85, ['qvpit', 'jlonsf', 'axnnpf', 'fmdmn']),
            new Tower('dojoi', 80, ['jimcygz', 'mhmbmve', 'wormisx', 'ejqqxk']),
            new Tower('tcewj', 125, ['rgicvct', 'wcvuu']),
            new Tower('kvgsfj', 89),
            new Tower('ythizc', 35),
            new Tower('mnxqlwj', 149, ['srwgf', 'pqhdp']),
            new Tower('cpjwxir', 50),
            new Tower('iwvzne', 85, ['silwij', 'ecilwqw', 'nxvhzm', 'iollvjh']),
            new Tower('nnpndet', 54),
            new Tower('kuoluj', 82),
            new Tower('fzcts', 68),
            new Tower('xerinl', 15),
            new Tower('mvacic', 6, ['tqxwy', 'dckpb', 'dlksv']),
            new Tower('tisslxr', 824, ['ysseykl', 'ydwug', 'zoawdu']),
            new Tower('fssxj', 82, ['vgxptd', 'myhzuy', 'pkyos', 'rclvfez']),
            new Tower('yolrl', 82),
            new Tower('ogrpc', 81),
            new Tower('tzcosab', 76),
            new Tower('vdbcedp', 92),
            new Tower('flsxmc', 2200, ['qqlkwr', 'knayoo']),
            new Tower('rfxjtuw', 93),
            new Tower('njfzhmg', 45),
            new Tower('howjlo', 78),
            new Tower('wbftdq', 85, ['dutfal', 'lcxllj']),
            new Tower('brtxkgi', 76),
            new Tower('wspsxh', 211),
            new Tower('ibasy', 44),
            new Tower('whboh', 88, ['fawih', 'hthizhf']),
            new Tower('weohqnq', 6219, ['sibzbaw', 'gaijq', 'oxpphmz', 'cdbqrv', 'vaexiu', 'ghzfclb', 'dlgyd']),
            new Tower('svmplb', 18),
            new Tower('nglzp', 39),
            new Tower('sctwwty', 69),
            new Tower('gdndx', 193),
            new Tower('lgqhttl', 323, ['hzmiprs', 'yqgwle']),
            new Tower('yktkkr', 98),
            new Tower('zzjap', 88, ['mpgup', 'zeohg']),
            new Tower('uylmxqo', 38, ['pjcluy', 'bqpjwai']),
            new Tower('xxshfpr', 86),
            new Tower('vgxptd', 67),
            new Tower('kgpoyb', 157, ['llowph', 'gnetslx']),
            new Tower('vspbcnk', 236, ['fvyctke', 'nrqmk', 'vbsku']),
            new Tower('iowckgn', 75),
            new Tower('zstxoet', 85),
            new Tower('zjkdtrq', 8),
            new Tower('ddmyid', 95),
            new Tower('zeohg', 72),
            new Tower('wwmta', 16),
            new Tower('ewbgxj', 28),
            new Tower('urvedm', 6),
            new Tower('lkijuws', 229, ['lqzhrg', 'ugyjqg']),
            new Tower('mzvna', 32),
            new Tower('yiwuei', 249),
            new Tower('htzdq', 65),
            new Tower('tnmziio', 60),
            new Tower('crghfz', 37, ['pdqvd', 'xvmstn']),
            new Tower('llocrvp', 9),
            new Tower('oprfjt', 171, ['gbwuf', 'otipnbc']),
            new Tower('umkwa', 21),
            new Tower('ustmeld', 13),
            new Tower('pomeveh', 21),
            new Tower('squxhq', 25),
            new Tower('wbbus', 72),
            new Tower('rclvfez', 67),
            new Tower('hevef', 37),
            new Tower('lsxavn', 91),
            new Tower('bqzpg', 90),
            new Tower('fdvks', 83),
            new Tower('tatyvy', 44),
            new Tower('hufovxb', 54, ['spxqd', 'hturdef']),
            new Tower('wniti', 11),
            new Tower('fxjacfb', 43),
            new Tower('nmpojs', 15),
            new Tower('lbmqte', 298, ['zebtnox', 'ustmeld', 'kkidtmk', 'enjhfeg']),
            new Tower('cnsemxt', 66),
            new Tower('izvxax', 78),
            new Tower('cnafwov', 93),
            new Tower('iefgdb', 39),
            new Tower('ivpbt', 217),
            new Tower('cdlnovn', 98),
            new Tower('gxnvl', 93),
            new Tower('ziiojfl', 155, ['lhdgv', 'vkvsku']),
            new Tower('pnbyuu', 18),
            new Tower('pnxkdii', 38),
            new Tower('nlzqs', 48),
            new Tower('mnkholz', 54, ['ymfxsdp', 'lqdrs']),
            new Tower('cehuzkr', 27),
            new Tower('lnfyg', 95),
            new Tower('vmcib', 82),
            new Tower('losxko', 93),
            new Tower('mlvywui', 30, ['zyeqj', 'kmrsi', 'vvqpt']),
            new Tower('czrbivk', 29),
            new Tower('avufwe', 59),
            new Tower('iecbxj', 18),
            new Tower('mhxka', 25),
            new Tower('xuxtbe', 21),
            new Tower('skcmxwu', 72),
            new Tower('pkmya', 47),
            new Tower('qiediji', 73),
            new Tower('gzldofv', 32),
            new Tower('rgiaar', 34),
            new Tower('vmcicx', 94),
            new Tower('zwpqdpp', 38),
            new Tower('qwrruob', 133, ['jcjsn', 'xerinl', 'czzvje', 'njimb']),
            new Tower('lwemj', 6, ['rgkzdr', 'qqqxi', 'uypwb', 'radrzr']),
            new Tower('oymgkey', 354, ['blrgxsb', 'pfamjeh']),
            new Tower('tykkgvz', 14, ['wterb', 'kvmxpmx', 'ecsdihr']),
            new Tower('zffpdg', 38),
            new Tower('gznay', 79),
            new Tower('yhbpsay', 186, ['tcgjhh', 'leubrjl', 'ihxtg', 'ijcvtep']),
            new Tower('nvqjado', 204, ['jvkpk', 'omzye']),
            new Tower('lstxl', 76),
            new Tower('tshems', 16),
            new Tower('zqdnix', 55),
            new Tower('hefczgn', 50, ['phqiqi', 'atcrb']),
            new Tower('uagtgt', 65),
            new Tower('ssnkl', 95, ['aglfaj', 'jtqcbjx']),
            new Tower('zyeqj', 66),
            new Tower('pbqrv', 75, ['qqfxsbl', 'jijzbp', 'gdvydrc']),
            new Tower('jbcaxyl', 54),
            new Tower('otlvpiq', 46, ['velbwcl', 'ypxvo', 'qgwyq', 'mtpicwi']),
            new Tower('krldk', 97, ['akyffva', 'nlzqs']),
            new Tower('knayoo', 59),
            new Tower('meyihxo', 98),
            new Tower('zjovf', 43),
            new Tower('opluk', 6),
            new Tower('lqzhrg', 10),
            new Tower('nnayovj', 268, ['wxnwn', 'stpwv', 'gymdygg']),
            new Tower('revfs', 62),
            new Tower('kssnbr', 63, ['llsqcnz', 'kdkng']),
            new Tower('qfuqfre', 217),
            new Tower('naheh', 39),
            new Tower('jzyfyj', 33),
            new Tower('rvzug', 124, ['jbcaxyl', 'nnpndet']),
            new Tower('hdkyjhw', 42),
            new Tower('xpmraw', 1409, ['xulssc', 'ectqv', 'votqgct']),
            new Tower('llowph', 58),
            new Tower('jmnxhqh', 93),
            new Tower('ahdgqpm', 833, ['dybapm', 'crlyq', 'cjixx']),
            new Tower('pqhdp', 31),
            new Tower('kmecjf', 15),
            new Tower('jggkrpf', 309, ['yuecj', 'nvxbdd', 'xlxroru', 'wfzkd']),
            new Tower('fgihxex', 90),
            new Tower('gaijq', 675, ['jdooxot', 'hkcuz', 'wgmxwy', 'iclrood', 'jmwrcxe']),
            new Tower('yruivis', 2760, ['oxipms', 'ggpau', 'sphbbz']),
            new Tower('dnomd', 92),
            new Tower('dymsh', 63),
            new Tower('ygjbwu', 235, ['hbnjvi', 'uiakb']),
            new Tower('jmpqot', 93),
            new Tower('lqdrs', 61),
            new Tower('sitbr', 57, ['fssxj', 'yhbpsay', 'jvmpc', 'lnhrx', 'ydtqhd', 'lbmqte', 'dmxqneb']),
            new Tower('nkikn', 6),
            new Tower('trrrswp', 95, ['rcssnrj', 'chtiq']),
            new Tower('qynklua', 23),
            new Tower('jdenl', 29),
            new Tower('qbvlzq', 77),
            new Tower('yvpvvx', 84),
            new Tower('huide', 45),
            new Tower('cadkdj', 45),
            new Tower('bcyxwt', 62),
            new Tower('dlgyd', 625, ['lzgjxpi', 'paguj', 'dkasko', 'pxkqb']),
            new Tower('atjgje', 63),
            new Tower('uiqegu', 6, ['gqzlx', 'pohvscs']),
            new Tower('wqcyyp', 66),
            new Tower('evauuqp', 23, ['rfowq', 'gwaym', 'mwkjo', 'fvcbh', 'mjvxc', 'bhcdq']),
            new Tower('irmrw', 521, ['vspbcnk', 'iebero', 'eshrket']),
            new Tower('dtdkt', 65),
            new Tower('mpgup', 72),
            new Tower('ppepf', 48),
            new Tower('kxegssv', 22),
            new Tower('ljvipn', 33),
            new Tower('azokid', 69),
            new Tower('ovxnqnd', 96, ['lgsulw', 'xwdlxg', 'vfkff', 'rsidt', 'vdcnit']),
            new Tower('gioryg', 77, ['mldtvex', 'ihcolp']),
            new Tower('gdvydrc', 56),
            new Tower('cunseqy', 38),
            new Tower('itnut', 161, ['flcth', 'hjlabl']),
            new Tower('psfpl', 38),
            new Tower('hmkoeo', 139, ['gzldofv', 'dteqv']),
            new Tower('kptyuf', 74, ['opyjeyu', 'xqeqnpv']),
            new Tower('vdxvll', 19),
            new Tower('kwymyn', 702, ['dvkug', 'ndjbiq', 'kykqehq']),
            new Tower('unkckgx', 201, ['fuitrtz', 'atbdhm']),
            new Tower('rfmuffd', 132, ['fixda', 'uesefn']),
            new Tower('knbeerh', 83),
            new Tower('sheuujc', 84),
            new Tower('qlfars', 161, ['dkzlr', 'kbhig']),
            new Tower('uaourd', 48),
            new Tower('fmdmn', 73),
            new Tower('wlauod', 252),
            new Tower('ppgcgz', 2965, ['dusyrs', 'bblhcmt', 'otlvpiq']),
            new Tower('nhhqfzk', 38),
            new Tower('rabaw', 68),
            new Tower('casskdk', 47),
            new Tower('fekljc', 24, ['yvpvvx', 'egbjx']),
            new Tower('kgjzt', 29),
            new Tower('arpzsz', 27, ['omivhf', 'sviek']),
            new Tower('vlbxwof', 63),
            new Tower('zfzpy', 28),
            new Tower('wtsgud', 51),
            new Tower('thsdq', 46),
            new Tower('kmrsi', 66),
            new Tower('dmoexuj', 52),
            new Tower('gxwqiat', 43),
            new Tower('ndjbiq', 276),
            new Tower('bqpjwai', 32),
            new Tower('licetbw', 145, ['ruahai', 'yzrlkj', 'vchfk', 'sgjljt']),
            new Tower('hzoqij', 174, ['cjusyky', 'ogltzt']),
            new Tower('ltgylh', 18),
            new Tower('xnzmf', 1127, ['arsrlmc', 'fljico', 'imcujsr', 'soutui']),
            new Tower('jgqxt', 93),
            new Tower('omzye', 14),
            new Tower('yaeji', 96),
            new Tower('lokxju', 53),
            new Tower('mkwoc', 377),
            new Tower('vjycok', 33),
            new Tower('bblhcmt', 1015, ['teduvz', 'mkcxutj', 'taaibzy']),
            new Tower('wzfzy', 95),
            new Tower('yjxiv', 30),
            new Tower('ixmsn', 74),
            new Tower('vopoojk', 52),
            new Tower('wzjwo', 145, ['kxegssv', 'mzymfht', 'etgpwm']),
            new Tower('sdosxki', 74),
            new Tower('lluca', 96),
            new Tower('mflxo', 21),
            new Tower('soutui', 60, ['cunseqy', 'akunww', 'nhhqfzk', 'fteop']),
            new Tower('emgpu', 217, ['jljjh', 'bawyt', 'mmcebdy', 'hevef']),
            new Tower('zuhfs', 3655, ['irmrw', 'dyhtgng', 'rehpie']),
            new Tower('johqjt', 26),
            new Tower('ygvnuu', 43),
            new Tower('orozsek', 78),
            new Tower('xsauoti', 35),
            new Tower('ncrzjm', 41),
            new Tower('pxqgvjs', 31),
            new Tower('vcbcy', 49),
            new Tower('bpctu', 39, ['kfbxhd', 'dcdgsj', 'kzwcue', 'tuxmvw']),
            new Tower('vwtpihe', 270),
            new Tower('qytnj', 28),
            new Tower('gwaym', 47, ['rmqmme', 'kikqp', 'lkhbcfn']),
            new Tower('wfkbot', 92),
            new Tower('aqiun', 6),
            new Tower('vfepai', 2052, ['rpijm', 'smpoeov', 'kssnbr']),
            new Tower('ggpau', 91, ['mavpqd', 'vtthqum', 'qghnwdf', 'uobgk', 'muarank', 'cgldm']),
            new Tower('mkcxutj', 199, ['mcqnk', 'ltgylh', 'nigxeuz']),
            new Tower('nrbka', 85, ['giagung', 'yikfhvr']),
            new Tower('kykqehq', 90, ['khvwq', 'jmpqot']),
            new Tower('ccisqhk', 36),
            new Tower('xvqpfd', 81),
            new Tower('rgkzdr', 88),
            new Tower('xulssc', 7, ['vywee', 'njfzhmg', 'hjbghmi', 'huide']),
            new Tower('etrye', 68, ['bwujye', 'tcnrrg']),
            new Tower('mptzfm', 131, ['kauaro', 'gwqvxp']),
            new Tower('zilgfzu', 6),
            new Tower('qvzlvq', 52),
            new Tower('yscvt', 19),
            new Tower('lqxevih', 29),
            new Tower('tugui', 51),
            new Tower('qzohrj', 46),
            new Tower('oifwih', 13748, ['qrncpfb', 'czwja', 'nnayovj']),
            new Tower('khuqo', 15),
            new Tower('darha', 47),
            new Tower('fvyctke', 35),
            new Tower('egjriv', 228, ['kvqrdbr', 'vxrdwe']),
            new Tower('mzozybe', 49),
            new Tower('juifyyw', 74, ['cuvpk', 'fdoszd', 'uwmpw', 'qqbjpw']),
            new Tower('mldtvex', 70),
            new Tower('yuerovj', 82),
            new Tower('qifwjr', 65, ['tykkgvz', 'ghfsfzv', 'essizn']),
            new Tower('ftcizt', 36, ['oieio', 'hzmzm']),
            new Tower('oapztg', 14, ['awhtfnb', 'qymuwz', 'plfmb']),
            new Tower('renhdd', 86),
            new Tower('yfjtfc', 18),
            new Tower('qfrgkwt', 84),
            new Tower('dmxqneb', 65, ['vjxqtpi', 'ocauj', 'meeiw']),
            new Tower('akyffva', 48),
            new Tower('iwvjsf', 21),
            new Tower('mmkbh', 77),
            new Tower('qvpit', 73),
            new Tower('pexdlf', 60),
            new Tower('wygaxkm', 15),
            new Tower('sibzbaw', 204, ['cafcfnl', 'faendwk', 'zwrwngq', 'mnchjf', 'saifkw', 'wbftdq', 'hmkoeo']),
            new Tower('ipnwyh', 81, ['edsdrz', 'pqciwb', 'uiycup']),
            new Tower('bqbgocl', 85, ['rtbipng', 'yypsdby', 'nlirga', 'bgprkt']),
            new Tower('mjorwvu', 341, ['uvokiil', 'svcfwb', 'yqvqkjj']),
            new Tower('ngadrj', 143, ['qqckql', 'xrffbj']),
            new Tower('putxfkb', 5),
            new Tower('dmobhqz', 81),
            new Tower('guuvcz', 11),
            new Tower('pqciwb', 59),
            new Tower('hovodbo', 251, ['ibvrqj', 'oxshhlc']),
            new Tower('kysof', 28),
            new Tower('hwvglh', 34),
            new Tower('crlyq', 51, ['zhpbfcb', 'vdmpy', 'lbogwls', 'tucemlh']),
            new Tower('mbxchx', 55),
            new Tower('ymnqdi', 78),
            new Tower('yxzvg', 94),
            new Tower('stjjr', 52),
            new Tower('bgprkt', 41),
            new Tower('pnvym', 58),
            new Tower('fyxeenq', 25),
            new Tower('eshhfd', 5),
            new Tower('adygspa', 46),
            new Tower('zhpbfcb', 82),
            new Tower('mhhvcg', 83, ['sorhq', 'hzoqij', 'mvacic', 'fbhzkoh', 'uzpxmf', 'cmyrw', 'mmqyju']),
            new Tower('vwlcnv', 53),
            new Tower('ifylycs', 78),
            new Tower('hrobopm', 136, ['tzupdgb', 'onrklke']),
            new Tower('vgxaajp', 88),
            new Tower('lgowj', 58),
            new Tower('uypwb', 88),
            new Tower('ghfsfzv', 293),
            new Tower('otipnbc', 23),
            new Tower('gwlzolt', 50),
            new Tower('rtlvfb', 74),
            new Tower('pvrocec', 76),
            new Tower('vdmpy', 82),
            new Tower('grmps', 69),
            new Tower('jvwlo', 98),
            new Tower('stpwv', 238, ['fyxeenq', 'mhxka', 'awfrk', 'cxrjgg']),
            new Tower('gboqva', 31, ['chsgrkx', 'bqzpg']),
            new Tower('hpthw', 805, ['oegjhcg', 'iriepoo', 'rvzug', 'kptyuf', 'yefht']),
            new Tower('rsygg', 81, ['xtuocx', 'hdkyjhw']),
            new Tower('vfkff', 336, ['fzuomz', 'xbgyvu']),
            new Tower('nklype', 84),
            new Tower('oieio', 98),
            new Tower('fpzvpx', 46),
            new Tower('dndusk', 349, ['pzpybas', 'rdiysu']),
            new Tower('njzaj', 40, ['lgqhttl', 'zrprsn', 'iwvzne', 'ohixl', 'dndusk']),
            new Tower('eeucvf', 58),
            new Tower('jlonsf', 73),
            new Tower('tuuzkn', 70),
            new Tower('zoawdu', 94, ['ongsjaf', 'zmfeb', 'sgnexg']),
            new Tower('xwslnr', 210, ['rtlvfb', 'gcdbb']),
            new Tower('kfbxhd', 81),
            new Tower('plfmb', 74),
            new Tower('ixhnyqi', 65),
            new Tower('jjhqu', 365),
            new Tower('pzxhsq', 25),
            new Tower('bkuxrk', 29),
            new Tower('fnjdau', 222, ['vsuyxah', 'rabaw']),
            new Tower('qycgu', 96, ['mfgpyyw', 'darha']),
            new Tower('ccqhl', 1886, ['tvranal', 'cjzstd', 'wbpvo']),
            new Tower('ohixl', 353, ['kyvqypb', 'boqtus']),
            new Tower('tuxmvw', 81),
            new Tower('ycoeh', 54),
            new Tower('prjag', 72),
            new Tower('hvfav', 98),
            new Tower('tvuey', 85),
            new Tower('gpsaq', 1408, ['amulani', 'kepgi', 'kyoopc']),
            new Tower('aende', 88, ['hsnkmd', 'qbvlzq', 'rpdrdxo']),
            new Tower('lupel', 72),
            new Tower('hqvbm', 47),
            new Tower('sygrs', 93),
            new Tower('gbwuf', 23),
            new Tower('wyiofd', 50),
            new Tower('yzrlkj', 23),
            new Tower('tjurw', 23, ['rfxjtuw', 'zujwuu', 'jhztf', 'cnafwov']),
            new Tower('zwjdka', 35),
            new Tower('kcqxplp', 18),
            new Tower('gtzxxav', 8936, ['sxppnu', 'jddjjw', 'biibrbq', 'ttldnhl']),
            new Tower('hpboonp', 33),
            new Tower('cdzfql', 55),
            new Tower('infjgg', 109, ['szyzmuw', 'zfzpy']),
            new Tower('nkohugb', 84),
            new Tower('eemxdkb', 76),
            new Tower('dusyrs', 1024, ['ztfziz', 'pxpuiaz', 'rfmuffd']),
            new Tower('nwsecpl', 90),
            new Tower('sdawsdp', 6, ['aaalewd', 'wzfzy', 'lnfyg']),
            new Tower('dypjwz', 34),
            new Tower('aahmp', 23),
            new Tower('grcpk', 26),
            new Tower('zujwuu', 93),
            new Tower('wiwrw', 51),
            new Tower('cgldm', 406, ['gludbju', 'wsstaru']),
            new Tower('kedwhhj', 52),
            new Tower('rsidt', 66, ['xvqpfd', 'kbcjy', 'exyceo', 'mbymo']),
            new Tower('tcndbu', 96, ['ihbeh', 'flyaq', 'pruqcvk', 'xxelf']),
            new Tower('srozw', 96),
            new Tower('tcgjhh', 41),
            new Tower('rtbipng', 41),
            new Tower('lyqumu', 84, ['pnvym', 'owjht', 'eeucvf']),
            new Tower('aokguyj', 88, ['skcmxwu', 'viofo']),
            new Tower('hjgfxun', 29),
            new Tower('ezxakj', 112),
            new Tower('svcfwb', 18),
            new Tower('yaqfv', 217),
            new Tower('hzmzm', 98),
            new Tower('lyxqyl', 2947, ['yffcj', 'zncyr', 'buaue', 'qesuv']),
            new Tower('uxpblf', 214, ['ehttqe', 'cleda', 'revfs', 'bcyxwt']),
            new Tower('ehttqe', 62),
            new Tower('dghbo', 59, ['itnut', 'oopqud', 'gmtkf', 'kgpoyb', 'wtioxkx', 'wajjyev', 'rqswk']),
            new Tower('ntnqvtk', 92),
            new Tower('yeojp', 85),
            new Tower('gmtkf', 126, ['pmjoye', 'dpbywy', 'vhfqi']),
            new Tower('fpmzgvo', 44),
            new Tower('rsmvde', 46),
            new Tower('hghnmv', 18),
            new Tower('lkuphpg', 48, ['dnomd', 'vdvwz']),
            new Tower('inilfk', 282, ['swshl', 'pzxhsq']),
            new Tower('ftloq', 44),
            new Tower('hbsdlm', 26),
            new Tower('lelwu', 81),
            new Tower('qqvrhv', 28),
            new Tower('czwja', 87, ['fqhegd', 'rzqtfk', 'tpldx', 'hrwhc', 'rklqa']),
            new Tower('tenewcj', 93),
            new Tower('iriepoo', 88, ['wbbus', 'julhx']),
            new Tower('flyaq', 34),
            new Tower('jtxkj', 55),
            new Tower('kauaro', 38),
            new Tower('dteqv', 32),
            new Tower('ibvain', 96),
            new Tower('isceom', 46),
            new Tower('fpdttlv', 249, ['iwvjsf', 'bqrvhzi']),
            new Tower('ibvrqj', 72),
            new Tower('avlhpbs', 91),
            new Tower('zotzrjn', 97),
            new Tower('vjzph', 53),
            new Tower('edswm', 5),
            new Tower('bhcdq', 62, ['vdbcedp', 'xxdnojb', 'wfkbot']),
            new Tower('hhgrgoa', 38),
            new Tower('yqvqkjj', 18),
            new Tower('mdpdynj', 83),
            new Tower('dtfayu', 217),
            new Tower('gedohd', 263, ['ogilk', 'hjwyc']),
            new Tower('uihrkc', 44),
            new Tower('bskomwv', 35),
            new Tower('lzgjxpi', 66, ['huwrhd', 'guaulxm']),
            new Tower('kihst', 30),
            new Tower('npqwie', 56, ['vgxaajp', 'zhfpuu']),
            new Tower('jijzbp', 56),
            new Tower('wonxy', 78),
            new Tower('hjsyte', 207, ['urgfd', 'mfdpgv', 'uaourd', 'cmgfqkb']),
            new Tower('vmebh', 21),
            new Tower('ueyxaa', 57, ['gxfqm', 'llocrvp']),
            new Tower('hzmiprs', 31),
            new Tower('mvqoekw', 21),
            new Tower('mmfwbku', 60, ['dymsh', 'nzmzrf', 'aealnl']),
            new Tower('ltiabeu', 63),
            new Tower('uniifn', 68),
            new Tower('trotdqj', 43),
            new Tower('pdyhl', 699, ['wzjwo', 'phkhvmp', 'gboqva', 'mnxqlwj', 'gtmfflw', 'wspsxh']),
            new Tower('uaztc', 1629, ['amwlt', 'mkjdh', 'ebjlbr']),
            new Tower('pmlho', 98),
            new Tower('zparvpi', 713, ['zjurdqp', 'uajyksv', 'nrbka', 'nvpsm']),
            new Tower('yztcfw', 93),
            new Tower('eshrket', 53, ['lluca', 'zntrxf', 'yaeji']),
            new Tower('flcth', 56),
            new Tower('spuzkk', 84),
            new Tower('kgntkz', 149, ['gwlzolt', 'ithtabv']),
            new Tower('xvtvomy', 81),
            new Tower('ratsida', 38),
            new Tower('ybtsie', 23),
            new Tower('qpfup', 53),
            new Tower('ovzoej', 129, ['emszr', 'olaxe']),
            new Tower('tdqqjpg', 83, ['evauuqp', 'iunpq', 'douxy', 'zfkfc']),
            new Tower('akunww', 38),
            new Tower('rjzvwv', 21),
            new Tower('rwtyr', 35),
            new Tower('bptimbu', 46),
            new Tower('vyufo', 65, ['eemxdkb', 'mdpwa']),
            new Tower('jgnvooj', 51),
            new Tower('tbnuh', 35),
            new Tower('siykhg', 287, ['kizgz', 'ratsida']),
            new Tower('wjccpg', 99),
            new Tower('qqbjpw', 97),
            new Tower('zntrxf', 96),
            new Tower('fgoqtbj', 61),
            new Tower('bawyt', 37),
            new Tower('voqlc', 104, ['rmilbmd', 'hxzqgfl', 'zkyvs']),
            new Tower('rmbnnq', 75),
            new Tower('fyqftv', 30),
            new Tower('xztwenv', 36),
            new Tower('votqgct', 187),
            new Tower('diccfps', 47),
            new Tower('fawih', 12),
            new Tower('czzvje', 15),
            new Tower('ujacw', 91, ['ckddz', 'ccisqhk', 'yedpzj']),
            new Tower('lzkcsih', 90),
            new Tower('fdplo', 56),
            new Tower('xniyrk', 194, ['npkqzzg', 'cqcqid']),
            new Tower('vtthqum', 312, ['syxaall', 'avufwe']),
            new Tower('hbnjvi', 28),
            new Tower('rmilbmd', 76),
            new Tower('oxshhlc', 72),
            new Tower('sykqu', 230),
            new Tower('joruazf', 35),
            new Tower('syxaall', 59),
            new Tower('wzqcv', 58),
            new Tower('xwuvr', 207, ['vmcicx', 'vcumw']),
            new Tower('niuzt', 5718, ['zdtby', 'imnmqmc', 'scurl', 'ovxnqnd']),
            new Tower('wxnwn', 312, ['efwsj', 'hnszth']),
            new Tower('xgjyuie', 211, ['wlauod', 'rkotan', 'lcltlz', 'yfkfk', 'vpuxpxj', 'remft', 'spagr']),
            new Tower('cdbqrv', 75, ['xewgja', 'dvkjfk', 'oxpmdnr', 'sultgf', 'pmwzrxm']),
            new Tower('mfdpgv', 48),
            new Tower('gumtctd', 90),
            new Tower('adckzt', 24),
            new Tower('dlksv', 64),
            new Tower('npkqzzg', 21),
            new Tower('yqjtia', 148, ['xxikrr', 'jxcxf', 'bqgxg']),
            new Tower('zebtnox', 13),
            new Tower('ecilwqw', 75),
            new Tower('vjjhef', 15),
            new Tower('pgfgtwj', 73),
            new Tower('tqxwy', 64),
            new Tower('xqeqnpv', 79),
            new Tower('krcdkw', 34),
            new Tower('cjzstd', 113, ['pkmya', 'eeuykqk']),
            new Tower('nzygm', 18),
            new Tower('crnvz', 1261, ['etrye', 'zjpzq', 'uaajucq', 'hefczgn']),
            new Tower('udiibbj', 78),
            new Tower('bncdhrm', 3810, ['nnbcnzu', 'qsnwd', 'axsupxp']),
            new Tower('xfcaona', 20, ['orozsek', 'vzhdg', 'ifylycs', 'howjlo']),
            new Tower('atbdhm', 89),
            new Tower('drwyz', 13),
            new Tower('ryclgvc', 73),
            new Tower('fxhtvj', 38),
            new Tower('fqhegd', 65, ['lgowj', 'wlrdp', 'wzqcv']),
            new Tower('blzatj', 154, ['zodnkd', 'jvlrpy']),
            new Tower('ongsjaf', 96),
            new Tower('cqakc', 131, ['lnddtya', 'ghhfd']),
            new Tower('yedpzj', 36),
            new Tower('taslihw', 198, ['nglzp', 'naheh']),
            new Tower('pxkqb', 80, ['zstxoet', 'tzypui']),
            new Tower('zkbdn', 16),
            new Tower('pkktbxs', 81),
            new Tower('jklwqzz', 90, ['hbsdlm', 'johqjt', 'ukjzi']),
            new Tower('mtwvvup', 301, ['psfpl', 'ywctcn']),
            new Tower('xbgyvu', 27),
            new Tower('clvvt', 90),
            new Tower('ugmfrt', 307, ['vwtpihe', 'sohtd', 'yluell', 'zrltc', 'bmfcc', 'dresa', 'httspr']),
            new Tower('cmyrw', 138, ['vnqxpf', 'kihst']),
            new Tower('sohtd', 156, ['zspyg', 'ylzdc']),
            new Tower('httspr', 212, ['czrbivk', 'hjgfxun']),
            new Tower('bdkcdaq', 64),
            new Tower('awhtfnb', 74),
            new Tower('pxpuiaz', 250),
            new Tower('ymfxsdp', 61),
            new Tower('pmjoye', 49),
            new Tower('zodnkd', 7),
            new Tower('psdcdbm', 51),
            new Tower('gijrym', 18),
            new Tower('boqtus', 16),
            new Tower('pfamjeh', 13),
            new Tower('jtqcbjx', 78),
            new Tower('cleda', 62),
            new Tower('vltxhu', 72),
            new Tower('qubakh', 35),
            new Tower('ykiurcc', 69),
            new Tower('tzupdgb', 20),
            new Tower('hlcpmj', 90),
            new Tower('tromme', 35),
            new Tower('gqzlx', 81),
            new Tower('icurk', 153, ['ovlnitv', 'ivinyhh']),
            new Tower('oxpmdnr', 244, ['hpboonp', 'vjycok']),
            new Tower('pzpybas', 18),
        ];
    }

    public function getTowerWeight(Tower $tower): int
    {
        $weight = $tower->getWeight();

        foreach ($tower->getSupports() as $supportedTowerName) {
            $tower = $this->getTowerByName($supportedTowerName);
            $weight += $this->getTowerWeight($tower);
        }

        return $weight;
    }

    public function getTowerByName($supportedTowerName): Tower
    {
        return $this->input[$supportedTowerName];
    }

    /**
     * @return int[]
     */
    private function getSupportedWeights(Tower $tower): array
    {
        $unbalancedWeights = [];
        foreach ($tower->getSupports() as $supportedTowerName) {
            $unbalancedWeights[$supportedTowerName] = $this->getTowerWeight($this->getTowerByName($supportedTowerName));
        }

        return $unbalancedWeights;
    }
}
