version: '3'

services:
  php:
    image: php:8.2-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
    user: 1000:1000
  composer:
    image: composer
    working_dir: /var/www
    volumes:
      - .:/var/www
