<?php

declare(strict_types=1);

namespace Tests\Xmas2023\Day11;

use Jean85\AdventOfCode\Xmas2023\Day11\SpaceMap;
use PHPUnit\Framework\TestCase;

class SpaceMapTest extends TestCase
{
    public function testParse(): void
    {
        $input = $this->getInput();
        $spaceMap = SpaceMap::parse($input);

        $this->assertEquals(trim($input), $spaceMap->print());
    }

    public function testPrintExpanded(): void
    {
        $expanded = '....#........
.........#...
#............
.............
.............
........#....
.#...........
............#
.............
.............
.........#...
#....#.......';

        $spaceMap = SpaceMap::parse($this->getInput());

        $this->assertEquals($expanded, $spaceMap->expand()->print());
    }

    private function getInput(): string
    {
        return '...#......
.......#..
#.........
..........
......#...
.#........
.........#
..........
.......#..
#...#.....

';
    }
}
